In [1]:
import numpy

In [7]:
a = numpy.arange(3)
print(a)

# 求返回e的幂次方
print(numpy.exp(a))
# 开根号
print(numpy.sqrt(a))


[0 1 2]
[ 1.          2.71828183  7.3890561 ]
[ 0.          1.          1.41421356]


In [21]:
a = numpy.floor(10 * numpy.random.random((3, 4)))
print(a)
print(a.shape)

# 把a从矩阵变换到向量
a = a.ravel()
print(a)
print(a.shape)

# 变换shape到6,2
a.shape = (6, 2)
print(a)

# 变换shape到3,4，用resize
a.resize((3, 4))
print(a)

# 变换shape的时候，可以把最后一个参数写成-1，这样numpy会根据前面的几个参数，自动计算
print(a.reshape(4, -1))


[[ 9.  3.  2.  2.]
 [ 2.  9.  4.  8.]
 [ 9.  5.  2.  8.]]
(3, 4)
[ 9.  3.  2.  2.  2.  9.  4.  8.  9.  5.  2.  8.]
(12,)
[[ 9.  3.]
 [ 2.  2.]
 [ 2.  9.]
 [ 4.  8.]
 [ 9.  5.]
 [ 2.  8.]]
[[ 9.  3.  2.  2.]
 [ 2.  9.  4.  8.]
 [ 9.  5.  2.  8.]]
[[ 9.  3.  2.]
 [ 2.  2.  9.]
 [ 4.  8.  9.]
 [ 5.  2.  8.]]


In [28]:
# 矩阵的合并
a = numpy.floor(10 * numpy.random.random((2, 2)))
b = numpy.floor(10 * numpy.random.random((2, 2)))
print(a)
print(b)

# 行不动，加列
print(numpy.hstack((a, b)))

# 列不动，加行
print(numpy.vstack((a, b)))


[[ 5.  2.]
 [ 9.  2.]]
[[ 5.  3.]
 [ 5.  3.]]
[[ 5.  2.  5.  3.]
 [ 9.  2.  5.  3.]]
[[ 5.  2.]
 [ 9.  2.]
 [ 5.  3.]
 [ 5.  3.]]


In [37]:
a = numpy.floor(10 * numpy.random.random((2, 12)))
print(a)

# 按列分割，竖着切，3等分
print(numpy.hsplit(a, 3))
# 按列分割，竖着切，指定切割的地方(在index3和index4的地方分割)
print(numpy.hsplit(a, (3, 4)))

a = numpy.floor(10 * numpy.random.random((12, 2)))
print(a)
# 按行分割，横着切
print(numpy.vsplit(a, 3))


[[ 0.  0.  1.  0.  6.  1.  4.  5.  6.  3.  0.  0.]
 [ 0.  9.  7.  6.  0.  9.  5.  4.  4.  3.  1.  8.]]
[array([[ 0.,  0.,  1.,  0.],
       [ 0.,  9.,  7.,  6.]]), array([[ 6.,  1.,  4.,  5.],
       [ 0.,  9.,  5.,  4.]]), array([[ 6.,  3.,  0.,  0.],
       [ 4.,  3.,  1.,  8.]])]
[array([[ 0.,  0.,  1.],
       [ 0.,  9.,  7.]]), array([[ 0.],
       [ 6.]]), array([[ 6.,  1.,  4.,  5.,  6.,  3.,  0.,  0.],
       [ 0.,  9.,  5.,  4.,  4.,  3.,  1.,  8.]])]
[[ 9.  4.]
 [ 2.  7.]
 [ 1.  7.]
 [ 1.  7.]
 [ 0.  4.]
 [ 8.  8.]
 [ 1.  6.]
 [ 4.  7.]
 [ 8.  4.]
 [ 5.  4.]
 [ 9.  5.]
 [ 6.  2.]]
[array([[ 9.,  4.],
       [ 2.,  7.],
       [ 1.,  7.],
       [ 1.,  7.]]), array([[ 0.,  4.],
       [ 8.,  8.],
       [ 1.,  6.],
       [ 4.,  7.]]), array([[ 8.,  4.],
       [ 5.,  4.],
       [ 9.,  5.],
       [ 6.,  2.]])]
