In [1]:
import numpy


In [2]:
# 与
vector = numpy.array([5, 10, 15, 20])
equal_to_ten_and_five = (vector == 10) & (vector == 5)
print(equal_to_ten_and_five)


[False False False False]


In [3]:
# 或
vector = numpy.array([5, 10, 15, 20])
equal_to_ten_or_five = (vector == 10) | (vector == 5)
print(equal_to_ten_or_five)


[ True  True False False]


In [4]:
# 或
vector = numpy.array([5, 10, 15, 20])
equal_to_ten_or_five = (vector == 10) | (vector == 5)
vector[equal_to_ten_or_five] = 50
print(vector)

[50 50 15 20]


In [7]:
# 数据类型转换
vector = numpy.array(["1", "2", "3"])
print(vector.dtype)
print(vector)
vector = vector.astype(float)
print(vector.dtype)
print(vector)

<U1
['1' '2' '3']
float64
[ 1.  2.  3.]


In [8]:
# vector求和
vector = numpy.array([5, 10, 15, 20])
vector.sum()


50

In [9]:
# matrix求和
matrix = numpy.array([[5, 10, 15, ], [20, 25, 30], [35, 40, 45]])
matrix.sum()


225

In [12]:
# matrix每列或者每行单独求和
matrix = numpy.array([[5, 10, 15, ], [20, 25, 30], [35, 40, 45]])
print(matrix.sum(axis=0))
print(matrix.sum(axis=1))  # 行


[60 75 90]
[ 30  75 120]
