In [1]:
import numpy

In [6]:
# 第一种复制
a = numpy.arange(12)
print(a)
b = a
print(b is a)
b.shape = (3, 4)
# 对b的修改，同时也修改了a，也就是a和b是指向同一内存的
print(a.shape)
# a和c的id一样
print(id(a))
print(id(b))


[ 0  1  2  3  4  5  6  7  8  9 10 11]
True
(3, 4)
1378130794656
1378130794656


In [13]:
# 第二种复制
a = numpy.arange(12)
c = a.view()
c.shape = (3, 4)
# 对c的shape的修改，没有体现在a上
print(a.shape)
c[0, 3] = 9999
# 对c的值的修改，体现在了a上。说明a和c虽然指向不同内存，但是里面的数据是共用的
print(a)
# a和c的id不一样
print(id(a))
print(id(c))


(12,)
[   0    1    2 9999    4    5    6    7    8    9   10   11]
1378130796096
1378130795296


In [17]:
# 第三种复制
a = numpy.arange(12)
d = a.copy()
print(d is a)
# 对d的值的操作，没有影响a
d[0] = 9999
print(a)
# a和d的id不一样
print(id(a))
print(id(d))


False
[ 0  1  2  3  4  5  6  7  8  9 10 11]
1378130895696
1378130896016


In [26]:
data = numpy.floor(100 * numpy.random.random((3, 4)))
print(data)
# 找出最大值的index，axis的时候，按列查找
ind = data.argmax(axis=0)
print(ind)
# 根据ind找出最大值
data_max = data[ind, numpy.arange(data.shape[1])]
print(data_max)


[[  7.  13.  46.  32.]
 [ 61.  29.  82.  60.]
 [ 69.  69.  54.  36.]]
[2 2 1 1]
4
[ 69.  69.  82.  60.]


In [31]:
a = numpy.arange(0, 40, 10)
print(a)
# tile填充，用a的数据，填充(2,3)
b = numpy.tile(a, (2, 3))
print(b)
print(b.shape)


[ 0 10 20 30]
[[ 0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30]]
(2, 12)


In [41]:
a = numpy.array([[4, 3, 5], [1, 2, 1]])
print(a)
# 排序
b = numpy.sort(a, axis=1)
print(b)
# 排序
a.sort(axis=1)
print(a)
# 排序
a = numpy.array([4, 3, 1, 2])
# 排序完的index
j = numpy.argsort(a)
print(j)
# 排序完的a
print(a[j])


[[4 3 5]
 [1 2 1]]
[[3 4 5]
 [1 1 2]]
[[3 4 5]
 [1 1 2]]
[2 3 1 0]
[1 2 3 4]
