In [6]:
import numpy

numbers = numpy.array([1, 2, 3, 4])
print(numbers)
print(numbers.dtype)


[1 2 3 4]
int32


In [7]:
numbers = numpy.array([1, 2, 3, 4.0])
print(numbers)
print(numbers.dtype)


[ 1.  2.  3.  4.]
float64


In [1]:
numbers = numpy.array([1, 2, 3, '4'])
print(numbers)
print(numbers.dtype)


NameError: name 'numpy' is not defined

In [7]:
world_alcohol = numpy.genfromtxt("world_alcohol.txt", delimiter=",", dtype=str, skip_header=1)
print(world_alcohol)


[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Wine' '1.62']
 ..., 
 ['1987' 'Africa' 'Malawi' 'Other' '0.75']
 ['1989' 'Americas' 'Bahamas' 'Wine' '1.5']
 ['1985' 'Africa' 'Malawi' 'Spirits' '0.31']]


In [10]:
uruguay_other_1986 = world_alcohol[1,4]
third_country = world_alcohol[2,2,]
print(uruguay_other_1986)
print(third_country)

0.5
Cte d'Ivoire


In [12]:
vector = numpy.array([1,2,3,4])
print(vector[0:2])

[1 2]


In [16]:
# 取第二列
matrix = numpy.array([[5,10,15],[20,25,30],[35,40,45]])
print(matrix[:,1])

[10 25 40]


In [18]:
# 取第二，第三列
print(matrix[:,1:3])

[[10 15]
 [25 30]
 [40 45]]


In [19]:
 # 取第一二行的第二三列
print(matrix[0:2,1:3])

[[10 15]
 [25 30]]


In [23]:
# 判断
vector = numpy.array([5,10,15,20])
print(vector == 10)
# 过滤出==10的
equal_to_10 = (vector == 10)
print(vector[equal_to_10])

[False  True False False]
[10]


In [33]:
# 判断
matrix = numpy.array([[5,10,15],[20,25,30],[35,40,45]])
print(matrix == 25)

# 过滤出等于25的
equal_to_25 = (matrix == 25)
print(matrix[equal_to_25])

# 查看没有一行的第二列等于25
equal_to_25_column = (matrix[:,1] == 25)
print(equal_to_25_column)
# 过滤出这行
print(matrix[equal_to_25_column])
print(matrix[equal_to_25_column,:])

[[False False False]
 [False  True False]
 [False False False]]
[25]
[False  True False]
[[20 25 30]]
[[20 25 30]]
