In [1]:
import numpy

In [4]:
a = numpy.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
a.shape

(3, 5)

In [6]:
# a的维度
a.ndim

2

In [11]:
# a里面的数据的类型
a.dtype.name

'int32'

In [12]:
# a的size
a.size

15

In [13]:
# 创建初始值为0的ndarray
numpy.zeros((3, 4))


array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [14]:
# 初始值为1的ndarray，数据类型指定为int
numpy.ones((2, 3, 4), dtype=numpy.int32)


array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [15]:
# arange，设定步长(左闭右开)
numpy.arange(10, 30, 5)


array([10, 15, 20, 25])

In [16]:
# arange，设定步长(左闭右开)
numpy.arange(0, 2, 0.3)


array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [17]:
# 随机
numpy.random.random((2, 3))


array([[ 0.80850302,  0.86970303,  0.42811335],
       [ 0.1430994 ,  0.97735063,  0.94134811]])

In [18]:
# linspace，参数：(开始值，结束值，分成多少份)
numpy.linspace(0, 2 * numpy.pi, 20)


array([ 0.        ,  0.33069396,  0.66138793,  0.99208189,  1.32277585,
        1.65346982,  1.98416378,  2.31485774,  2.64555171,  2.97624567,
        3.30693964,  3.6376336 ,  3.96832756,  4.29902153,  4.62971549,
        4.96040945,  5.29110342,  5.62179738,  5.95249134,  6.28318531])

In [24]:
# 对向量的一些计算
a = numpy.array([20, 30, 40, 50])
b = numpy.arange(4)
print(a)
print(b)

c = a - b
print(c)

b **= 2
print(b)

print(a < 35)


[20 30 40 50]
[0 1 2 3]
[20 29 38 47]
[0 1 4 9]
[ True  True False False]


In [26]:
# 矩阵的计算
A = numpy.array([[1, 1], [0, 1]])
B = numpy.array([[2, 0], [3, 4]])
print(A)
print(B)

# 相乘
print(A * B)

# 点乘
print(A.dot(B))
print(numpy.dot(A, B))


[[1 1]
 [0 1]]
[[2 0]
 [3 4]]
[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]
