In [13]:
import numpy

world_alcohol = numpy.genfromtxt("world_alcohol.txt",delimiter=",",dtype=str)
print(type(world_alcohol))
print(world_alcohol)
# print(help(numpy.genfromtxt))

<class 'numpy.ndarray'>
[['Year' 'WHO region' 'Country' 'Beverage Types' 'Display Value']
 ['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ..., 
 ['1987' 'Africa' 'Malawi' 'Other' '0.75']
 ['1989' 'Americas' 'Bahamas' 'Wine' '1.5']
 ['1985' 'Africa' 'Malawi' 'Spirits' '0.31']]


In [6]:
vector = numpy.array([5,10,15,20])
print(vector)

[ 5 10 15 20]


In [7]:
matrix = numpy.array([[5,10,15],[20,25,30]])
print(matrix)

[[ 5 10 15]
 [20 25 30]]


In [8]:
print(vector.shape)
print(matrix.shape)

(4,)
(2, 3)
